name: Jisticle
options:
  bundleIdPrefix: com.adamghill

packages:
  CodeEditor:
    url: https://github.com/ZeeZide/CodeEditor.git
    from: 1.0.0
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    from: 4.2.2
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: 2.1.0

targets:
  Jisticle:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/Jisticle
      - path: Sources/Jisticle/Assets.xcassets
        buildPhase: resources
    info:
      path: Sources/Jisticle/Info.plist
    settings:
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_ENTITLEMENTS: Sources/Jisticle/Jisticle.entitlements
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      CODE_SIGN_IDENTITY: "-"
      CODE_SIGN_STYLE: Manual
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: CodeEditor
        product: CodeEditor
      - package: KeychainAccess
        product: KeychainAccess
      - package: MarkdownUI
        product: MarkdownUI
